version: '3.8'
services:
  backend:
    container_name: steam_clone_backend
    image: krakenlink/be-centurion:v1
    restart: always
    env_file:
      - env
    ports:
      - "8080:8080"
    networks:
      - combine


  frontend:
    container_name: viteapp
    image: krakenlink/vite-app:v1
    restart: always
    networks:
      - combine

  nginx:
    image: nginx:alpine
    container_name: gate
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - frontend
      - backend
    networks:
      - combine

  networks:
    combine:
      driver: bridge

