version: '3.8'
services:
  backend:
    container_name: steam_clone_backend
    image: krakenlink/centurionbe:v1
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - combine
networks:
    combine:
      driver: bridge

