apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: centurion-be-monitor
  namespace: default
  labels:
    release: prometheus # (Bắt buộc phải có chữ này để Prometheus nhận diện)
spec:
  selector:
    matchLabels:
      app: centurion-be # <-- Chữ này phải GIỐNG HỆT cái label trong deployment.yaml của sếp
  endpoints:
  - port: http # <-- Tên cái port trong file service.yaml (Nếu sếp không đặt tên thì đổi thành targetPort: 8080)
    path: /actuator/prometheus
    interval: 15s