spring.application.name=Steam_CLone_DB
# SQL Server connection
# spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Steam_CLone_DB;encrypt=true;trustServerCertificate=true
spring.datasource.url=${SPRING_DATASOURCE_URL}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# JPA settings
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF
# or validate/update/create depending on your case
spring.jpa.show-sql=false

# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# for multipart file upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10GB
spring.servlet.multipart.max-request-size=20GB


spring.web.resources.static-locations=classpath:/resources/

# JWT settings
jwt.secret=kD2z!m9@R4v#Lx5fE1b$Nj7cV6a*Qh0sT3y&Wg8uZp
jwt.expirationMs=3600000  
# 1 hour

#Google OAuth2 configuration
spring.security.oauth2.client.registration.google.client-id=439938595818-d31nh6rmbscmllq6o9t662efh1eqjqkq.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

# Google Drive Configuration huy
gdrive.service_account.key_file_path=classpath:avatar-credential.json
gdrive.folder.avatars.id=14PygDsVyy_1lgjHtrK8YukcBTgrH-F6g
# Mail config for sending emails (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=5fcl.system@gmail.com
spring.mail.password=gnqo vaqc qdxg egic    
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# VNPAY Sandbox by TSHuy
vnpay.tmnCode=4QYEA4WS
vnpay.hashSecret=HM5PURUWYYR7SQEZ4TN59POBPNRO6MOG
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
# vnpay.returnUrl=http://localhost:5173/payment-result
vnpay.returnUrl=https://swp-391-frontend-forked-4fn59lpkw-minikies-projects.vercel.app/payment-result


logging.level.org.springframework.security=DEBUG
logging.level.com.se1933g01.steamclonebackend=DEBUG

#Frontend URL
frontend.url=https://swp-391-frontend-forked-4fn59lpkw-minikies-projects.vercel.app