name: CI/CD
on: 
    push:
        branches:
            - main
env:
  PROJECT_ID: "ppjg-236308"
  ZONE: "us-central1-a" 
  VM_NAME: "centurion" 
  IMAGE_URL: "krakenlink/centurionbe"
jobs:
    checkout:
        runs-on: ubuntu-24.04
        steps:
            - name: checkout-code
              uses: actions/checkout@v4
            - name: auth docker
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: build image
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: krakenlink/centurionbe:v1

    deploy:
        runs-on: ubuntu-24.04
        needs: checkout
        steps:
            - name: login gcp cli
              uses: google-github-actions/auth@v2
              with:
                credentials_json: ${{ secrets.GCP_SA_KEY }}
            - name: set up gcloud cli
              uses: google-github-actions/setup-gcloud@v2
            - name: create env file
              env:
                ENV: ${{secrets.ENV}}
              run: |
                echo "$ENV" > .env
            - name: update vm image
              run: |
                cat .env 
                gcloud compute instances update-container ${{ env.VM_NAME }} \
                  --container-image ${{ env.IMAGE_URL }}:v1 \
                  --zone ${{ env.ZONE }} \
                  --container-env-file=.env \
                  --port-mappings=8080:8080:TCP

              
              


                

    